### Site info:
title: Alex's Blog
tagline: Coffee, Code & more 
author: Alex Wittig
email: alexanderwittig@gmail.com
description: "" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alexandervvittig.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: alexvvittig
github_username:  alexandervvittig
favicon:     "/images/favicon.ico"
aboutme:  IT Professional, C8H10N4O2 lover, PowerShell enthusiast & expat #these are shown on aboutme-sidebar.
aboutme_photo: https://blog.vvittig.com/wp-content/uploads/2016/02/me.jpg # your photo.
google_analytics_key:  # put YOUR key here to enable tracking! (blank to disable)

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).

### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
